# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# for_005b_mangrove_extent_change.py
# Created on: 2021-05-20 12:13:42.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
GMW_2016_v2_shp = "C:\\Users\\RThoms.Local\\OneDrive - World Resources Institute\\Documents\\ArcGIS\\Source_data\\Indicators\\Mangroves\\GMW_001_GlobalMangroveWatch_2016\\GMW_001_GlobalMangroveWatch_2016\\01_Data\\GMW_2016_v2.shp"
mangrove_2016 = "C:\\Users\\RThoms.Local\\OneDrive - World Resources Institute\\Documents\\ArcGIS\\Indicators\\mangroves\\Mangrove.gdb\\GMW_2016_v2_Project"
GMW_1996_v2_shp = "C:\\Users\\RThoms.Local\\OneDrive - World Resources Institute\\Documents\\ArcGIS\\Source_data\\Indicators\\Mangroves\\GMW_001_GlobalMangroveWatch_1996\\GMW_001_GlobalMangroveWatch_1996\\01_Data\\GMW_1996_v2.shp"
mangrove_1996 = "C:\\Users\\RThoms.Local\\OneDrive - World Resources Institute\\Documents\\ArcGIS\\Indicators\\mangroves\\Mangrove.gdb\\GMW_1996_v2_Project"
mangrove_intersect = "C:\\Users\\RThoms.Local\\OneDrive - World Resources Institute\\Documents\\ArcGIS\\Indicators\\mangroves\\Mangrove.gdb\\GMW_1996_2016_Intersect"
stable_1 = mangrove_intersect
gain_1 = "C:\\Users\\RThoms.Local\\OneDrive - World Resources Institute\\Documents\\ArcGIS\\Indicators\\mangroves\\Mangrove.gdb\\GMW_2016_Erase"
gain_2 = gain_1
gain_3 = gain_2
stable_2 = stable_1
loss_1 = "C:\\Users\\RThoms.Local\\OneDrive - World Resources Institute\\Documents\\ArcGIS\\Indicators\\mangroves\\Mangrove.gdb\\GMW_1996_Erase"
loss_2 = loss_1
loss_3 = loss_2
mangrove_extent_change_shp = "C:\\Users\\RThoms.Local\\OneDrive - World Resources Institute\\Documents\\ArcGIS\\Modified_data\\Indicators\\mangrove_area\\mangrove_extent_change\\mangrove_extent_change.shp"

# Process: Project (2)
arcpy.Project_management(GMW_2016_v2_shp, mangrove_2016, "PROJCS['World_Cylindrical_Equal_Area',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Cylindrical_Equal_Area'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-160.0],PARAMETER['Standard_Parallel_1',0.0],UNIT['Meter',1.0]]", "", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "NO_PRESERVE_SHAPE", "", "NO_VERTICAL")

# Process: Project
arcpy.Project_management(GMW_1996_v2_shp, mangrove_1996, "PROJCS['World_Cylindrical_Equal_Area',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Cylindrical_Equal_Area'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-160.0],PARAMETER['Standard_Parallel_1',0.0],UNIT['Meter',1.0]]", "", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "NO_PRESERVE_SHAPE", "", "NO_VERTICAL")

# Process: Intersect
arcpy.Intersect_analysis("'C:\\Users\\RThoms.Local\\OneDrive - World Resources Institute\\Documents\\ArcGIS\\Indicators\\mangroves\\Mangrove.gdb\\GMW_1996_v2_Project' #;'C:\\Users\\RThoms.Local\\OneDrive - World Resources Institute\\Documents\\ArcGIS\\Indicators\\mangroves\\Mangrove.gdb\\GMW_2016_v2_Project' #", mangrove_intersect, "ALL", "", "INPUT")

# Process: Erase
arcpy.Erase_analysis(mangrove_2016, mangrove_intersect, gain_1, "")

# Process: Add Field
arcpy.AddField_management(gain_1, "Status", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(gain_2, "Status", "'gain'", "PYTHON_9.3", "")

# Process: Add Field (3)
arcpy.AddField_management(mangrove_intersect, "Status", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(stable_1, "Status", "'stable'", "PYTHON_9.3", "")

# Process: Erase (2)
arcpy.Erase_analysis(mangrove_1996, mangrove_intersect, loss_1, "")

# Process: Add Field (2)
arcpy.AddField_management(loss_1, "Status", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(loss_2, "Status", "'loss'", "PYTHON_9.3", "")

# Process: Merge
arcpy.Merge_management("'C:\\Users\\RThoms.Local\\OneDrive - World Resources Institute\\Documents\\ArcGIS\\Indicators\\mangroves\\Mangrove.gdb\\GMW_2016_Erase';'C:\\Users\\RThoms.Local\\OneDrive - World Resources Institute\\Documents\\ArcGIS\\Indicators\\mangroves\\Mangrove.gdb\\GMW_1996_2016_Intersect';'C:\\Users\\RThoms.Local\\OneDrive - World Resources Institute\\Documents\\ArcGIS\\Indicators\\mangroves\\Mangrove.gdb\\GMW_1996_Erase'", mangrove_extent_change_shp, "Status \"Status\" true true false 0 Text 0 0 ,First,#,C:\\Users\\RThoms.Local\\OneDrive - World Resources Institute\\Documents\\ArcGIS\\Indicators\\mangroves\\Mangrove.gdb\\GMW_2016_Erase,Status,-1,-1,C:\\Users\\RThoms.Local\\OneDrive - World Resources Institute\\Documents\\ArcGIS\\Indicators\\mangroves\\Mangrove.gdb\\GMW_1996_2016_Intersect,Status,-1,-1,C:\\Users\\RThoms.Local\\OneDrive - World Resources Institute\\Documents\\ArcGIS\\Indicators\\mangroves\\Mangrove.gdb\\GMW_1996_Erase,Status,-1,-1")

